name: Terence Kohler
favicon: null
layout_spectrum: 0.21959
typography_spectrum: 0.4746485014911741
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#354a75'
    - '#86a4d5'
    - '#dddddd'
    - '#7a6560'
  brandStrength: 0
  lightness: 0.25
  saturation: 0.375
  rhythmicContrast: 1
purpose: []
